### ISSUE TITLE
Could you please add a License?

### ISSUE THREAD

**Issue by mondjunge** [kira2040k/php_code_analysis#7]
I would like to add your script to my own repository at https://gitlab.com/mondjunge/Crush-Framework. 
It would not be part of the software, but a helping tool for security audits.
Without License this is a no-go, obviously.
 
MIT would be appropriate, I guess...
Take a look at the candidates and what they have to offer: https://choosealicense.com/licenses/

**Comment by kira2040k** [comment]
done
